<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>NetDevs.EntityFrameworkCore.Auditing</AssemblyName>
		<RootNamespace>NetDevs.EntityFrameworkCore.Auditing</RootNamespace>
		<PackageId>NetDevs.EntityFrameworkCore.Auditing</PackageId>
		<Version>1.0.0</Version>
		<Authors>Sebastian Wnorowski</Authors>
		<Description>EF Core auditing based on SaveChangesInterceptor.</Description>
		<PackageTags>efcore;auditing;interceptor;savechanges;clean-architecture</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<PropertyGroup>
		<DebugType>full</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\NetDevs.Domain.Abstractions\NetDevs.Domain.Abstractions.csproj" />
	</ItemGroup>

</Project>
