<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AssemblyName>NetDevs.QueryableProcessor</AssemblyName>
		<RootNamespace>NetDevs.QueryableProcessor</RootNamespace>
		<PackageId>NetDevs.QueryableProcessor</PackageId>
		<Version>1.0.0</Version>
		<Authors>Sebastian Wnorowski</Authors>
		<Description>A powerful library for dynamic filtering, sorting, and pagination of IQueryable collections.</Description>
		<PackageTags>LINQ IQueryable Sorting Filtering Pagination Dynamic</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<PropertyGroup>
		<DebugType>full</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>

</Project>
